### ISSUE TITLE
Maven repository is empty for version 1.1.5_SNAPSHOT

### ISSUE THREAD

**Issue by Moddus** [vanderfox/alexa-skills-kit-java#4]
Hi,
I've you visit:
http://dl.bintray.com/vanderfox/alexa-skills-kit-java/com/amazon/alexa/alexa-skills-kit-java/1.1.5_SNAPSHOT/

There is no jar and pom file. I guess something went wrong and because of the I'm not able to update.

Thanks, for deliver an up to date version from the alexa-skills-kit-java!

**Comment by rvanderwerf** [comment]
Yes I will push the latest to bintray tonight,  I will close when done thanks for the reminder!

**Comment by rvanderwerf** [comment]
Published! Follow the docs on the main readme for adding the bintray repo to your project.
